name: SWA_$(Year:yyyy)$(Month:mm)$(Day:dd)$(Rev:.r)

trigger: # runs on changes
  branches:
    include:
      - main

jobs: 
  - job: Deploy
    displayName: 'Build and Deploy SWA'

    pool: # build env (linux VM)
      vmImage: 'ubuntu-latest'

    variables: # references this variable group for environment data
      - group: Azure-Static-Web-Apps-green-field-0ab7dc600-variable-group

    steps:
      - checkout: self # checks out the repo including submodules
        submodules: true

      - task: AzureStaticWebApp@0 
        inputs:
          app_location: "src"
          output_location: "dist"
          azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN_GREEN_FIELD_0AB7DC600)
